---
- name: Install EPEL Repo
  hosts: servers
  become: true
  tasks:
  - name: Install EPEL Repo package from standard repo
    yum:
      name: epel-release
      state: present
  - name: Install Nginx
    yum:
      name: nginx
      state: present